### PR TITLE
phys: implement symbolic Dalitz phase space

### PR DESCRIPTION
**Pull request by redeboer**
Extracted from https://github.com/ComPWA/compwa-org/pull/129#issuecomment-1105117403. Preview of TR-017 [here](https://compwa-org--139.org.readthedocs.build/report/017.html).

- [x] Implement symbolic Kibble and Källén functions
- [x] Visualize 2D phase space boundary
- [x] Visualize 1D phase space projections
- [x] Add references to literature
- [x] Parametrize 2D phase space boundary (instead of contour plot over meshgrid)

<details>
<summary>Interactive visualization</summary>

</details>

### CODE REVIEW

**Comment by mmikhasenko** [comment]
>  (?) Parametrize 2D phase space boundary (instead of contour plot over meshgrid)

It is an analytic expression, easy to write down. I just do not know the best way to code it since, for whatever Mandelstam variable you choose for y axis, there is an expression y+-(x) where x is whatever you choose for x variable.

see
https://github.com/mmikhasenko/ThreeBodyDecay.jl/blob/01be61b5ab56f191e09f28c97f9e64755efe8bee/src/tbs_struct.jl#L172
with
https://github.com/mmikhasenko/ThreeBodyDecay.jl/blob/master/src/angle_functions.jl#L26

**Comment by redeboer** [comment]
Ah thanks for the links!

> I just do not know the best way to code it since, for whatever Mandelstam variable you choose for y axis, there is an expression y+-(x) where x is whatever you choose for x variable.

Do you mean sigma2 as a function of sigma1?
image

For plotting (with matplotlib), it would be better if there is some way to parametrize the closed boundary as a function of some variable _t_ along that boundary. But that would be harder to solve, if even possible.

**Comment by mmikhasenko** [comment]
uh, well done with the solve! :)

yes, there is one fun way for parametric coundary:

1. replace
 * sigma1 = (m2+m3)^2 + T1
 * sigma2 = (m3+m1)^2 + T2
 * sigma3 = (m1+m2)^2 + T3
Then, replace to r, theta to impose a constraint
image
where
T0 = m0^2+m1^2+m2^2+m3^2 - (m2+m3)^2 - (m3+m1)^2 - (m1+m2)^2 

for every value of \theta \in [0, 360], the value of r should be found numerically, by solving phi=0.

**Comment by mmikhasenko** [comment]
for the references,

Eero Byckling, K. Kajantie
https://inspirehep.net/literature/1251349

it is the particle-kinematics bible

**Comment by redeboer** [comment]
> Eero Byckling, K. Kajantie https://inspirehep.net/literature/1251349
> it is the particle-kinematics bible

Great tip! See 632d0c4

**Comment by redeboer** [comment]
> yes, there is one fun way for the parametric boundary:
> ...

Seems that this results in 3rd degree polynomials in _r_ (e626d3b). Well let's not bother to plot that then :P<br>
image

**Comment by redeboer** [comment]
Btw where is this from? Byckling and Kajantie do a similar trick for "all masses equal", but I can't see why this would work.

> 2\. Then, replace to r, theta to impose a constraint
>     image
>     where
>     T0 = m0^2+m1^2+m2^2+m3^2 - (m2+m3)^2 - (m3+m1)^2 - (m1+m2)^2

**Comment by mmikhasenko** [comment]
Yes, the idea is from Byckling-Kajantie.
I was giving similar exercises to students when I was teaching.

> I can't see why this would work.
you make the change of coordinates {sigma_i} -> {r,\phi} in the way that kinematic constraint 
```
sum_1^3 sigma_i = sum_0^3 m_j
```
is always satisfied. The exact transformation is from the `triangle` representation of the Dalitz.
{r,\phi} are polar cooridinates. I think, that r=0 is always physical.

Actually, it would be nice to see that it works by finding the root numerically.
I find it fascinating to see the polynomial itself. Before I only worked it out analytically for a few limited cases.

**Comment by redeboer** [comment]
@wgradl, once this PR is merged, this page can be found under [compwa-org.rtfd.io/report/017.html](https://compwa-org.readthedocs.io/report/017.html). Are there any things that can be improved before? Preview of the page [here](https://compwa-org--139.org.readthedocs.build/report/017.html).

**Comment by wgradl** [comment]
@redeboer, this looks very good to me!


> @wgradl, once this PR is merged, this page can be found under [compwa-org.rtfd.io/report/017.html](https://compwa-org.readthedocs.io/report/017.html). Are there any things that can be improved before? Preview of the page [here](https://compwa-org--139.org.readthedocs.build/report/017.html).
>

**Comment by mmikhasenko** [comment]
I just checked that the trick with minimal positive root works

image

the example is here
https://github.com/mmikhasenko/examples/blob/master/parametricDPboundary.jl

**Comment by redeboer** [comment]
Cool. I want to get #134 to work, so we can integrate such Julia scripts 😆 
Afaics, with matplotlib/python, this is harder to do with Python, because there isn't an equivalent to this `roots()` function. Moving this point to #142.

**Pull request merged**
