### PR TITLE
phys: investigate symbolic Dalitz Plot Decomposition

### PR DESCRIPTION
**Pull request by mmikhasenko**
_Preview can be viewed [here](https://compwa-org--133.org.readthedocs.build/report/019.html)._

The notebook is extended from the TR-018 (#129) to provide a different angle to the three-body decay distribution.

The unpolarized matrix element is casted to a bilinear form on dynamic function $R$ for every LS coupling.
Parity conservation is assumed.

### To-do list
 - [ ] generalize to arbitrary spins of the final particles
 - [ ] generalize to several isobars in subchannel
 - [ ] add the step from the angles to polynomials in the Mandelstam variables

### CODE REVIEW

**Comment by mmikhasenko** [comment]
I did not mean to call for the review yet, sorry, wrong click

**Comment by redeboer** [comment]
> @redeboer could you please help converting the notebook
> https://github.com/mmikhasenko/compwa-org/blob/dalitzdistribution/docs/report/018.ipynb
> to a nice page. I suppose some meta information is missing

It seems that the notebook is ok, there are just some bugs in the code itself
https://github.com/ComPWA/compwa-org/runs/6097062125?check_suite_focus=true#step:6:20
I'll have a look

**Comment by redeboer** [comment]
So the idea of this notebook is basically to implement a symbolic version of DPD without dynamics?

**Comment by mmikhasenko** [comment]
yes.
I am often asked how the angular distribution along the resonance looks like. One can also compute the angular expression for the interference. Most of the time it is surprisingly simple once all indices are summed up,

**Comment by mmikhasenko** [comment]
>  there are just some bugs in the code itself
that I can fix quickly. I need to teach myself to run the notebook thought before committing. haha

**Comment by redeboer** [comment]
Okay. It would be better to work this out in a more rigid way in a library (e.g. https://github.com/ComPWA/ampform/issues/277). But a report would be fine for now, to show that it works.

**Comment by mmikhasenko** [comment]
output was missing in several cells but I suppose the webpage is generated from scratch anyways. The code seems fine.

**Comment by mmikhasenko** [comment]
> Okay. It would be better to work this out in a more rigid way in a library (e.g. https://github.com/ComPWA/ampform/issues/277). But a report would be fine for now, to show that it works.

Certaintly.

**Comment by mmikhasenko** [comment]
Indeed

> I think ideally you need some data structure that contains all the info you need for each decay, like LS values in the production node and in the decay node and parent spin.

yes, that is what I did before with my julia code.
The only thing that the amplitude builder cares about is
 - `j0,j1,j2,j3`
 - `chain_ind`, `j`, `LS`, `ls`.
Later, for convenience one can compute possible `ls`, and `LS` based on the parities.

**Comment by mmikhasenko** [comment]
> If you have the installed a virtual environment with `dev` requirements

Do you mean
```
pip install -e .[dev]
```

not sure I installed the `dev`

**Comment by redeboer** [comment]
> Do you mean
> 
> ```
> pip install -e .[dev]
> ```
> 
> not sure I installed the `dev`

Yep. Or to be even safer:
```shell
pip install -e .[dev] -c .constraints/py3.8.txt  # your python version here
```

**Comment by redeboer** [comment]
> The only thing that the amplitude builder cares about is
> 
> * `j0,j1,j2,j3`
> * `chain_ind`, `j`, `LS`, `ls`.
>   Later, for convenience one can compute possible `ls`, and `LS` based on the parities.

88725fb encapsulates that info as a (mutable) class. Could be rewritten by nesting for instance. I didn't push more modifications to avoid merge conflicts.

**Pull request closed without merging**
